"""empty message

Revision ID: b559c2ab966f
Revises: 081987267877
Create Date: 2024-03-16 20:08:44.462427

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b559c2ab966f"
down_revision = "081987267877"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_one",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_one_id"), "task_one", ["id"], unique=False)
    op.create_table(
        "task_two",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_task_two_id"), "task_two", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_two_id"), table_name="task_two")
    op.drop_table("task_two")
    op.drop_index(op.f("ix_task_one_id"), table_name="task_one")
    op.drop_table("task_one")
    # ### end Alembic commands ###
