server {
    listen 80;
    server_name xaphan.ru www.xaphan.ru;

    return 301 https://$host$request_uri;
}



server {
    listen 443 ssl;

    server_name xaphan.ru, www.xaphan.ru;

    ssl_certificate /home/cert/certificate.pem;
    ssl_certificate_key /home/cert/private_key.pem;

    root /home/web/default;

    client_max_body_size 1000M;

    location /pgadmin {
        proxy_pass http://172.20.0.40:5123;
        proxy_set_header Host $host;
        proxy_set_header X-Script-Name /pgadmin;
        proxy_redirect off;
        proxy_intercept_errors on;
    }

    location /flower_first {
        proxy_pass http://172.20.0.41:5801;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_intercept_errors on;
    }

    location /flower_two {
        proxy_pass http://172.20.0.42:5802;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_intercept_errors on;
    }

    location /app11/ {
        proxy_pass http://172.20.0.11:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }

    location /app22/ {
        proxy_pass http://172.20.0.22:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }
}
