"""empty message

Revision ID: d1dbc662cd8c
Revises: 29b63e5ffe6d
Create Date: 2024-04-04 19:15:32.054704

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1dbc662cd8c"
down_revision = "29b63e5ffe6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_one", sa.Column("msg", sa.String(), nullable=True))
    op.drop_column("task_one", "author")
    op.drop_column("task_one", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_one",
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "task_one",
        sa.Column("author", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("task_one", "msg")
    # ### end Alembic commands ###
